### ISSUE TITLE
update student info - delete interest

### ISSUE THREAD

**Issue by dyanni** [moar55/se-project-testing#32]
1-Severity: Medium
2-Reported by: Daniel Yanni
3- Description: When a student tries to delete an empty interest he/she created. It will not be deleted. 
4- Steps to reproduce the issue: 1- login as a student 2- my profile 3- choose an empty interest. 4- submit. 
5- Expected Result: Interest should be deleted.

**Comment by safya-alzayat** [comment]
duplicate of https://github.com/moar55/se-project-testing/issues/70
