### ISSUE TITLE
As a student i can’t see any service providers

### ISSUE THREAD

**Issue by shadyaboud96** [moar55/se-project-testing#35]
1- high
2- Reported by Shady aboud
3- when i log in as a student i should be able to view the service providers.
4- log in as a student and try viewing the service providers.
5- i should be able to view the service providers.

**Comment by m-ohamed** [comment]
While logged in as a student:
1. Beside the search bar click on Business.
2. Leave the search field empty.
3. Press enter.

This should return a list of all the accepted service providers.

**Comment by safya-alzayat** [comment]
duplicate of https://github.com/moar55/se-project-testing/issues/1
