### ISSUE TITLE
Not working email

### ISSUE THREAD

**Issue by syrinehamza** [moar55/se-project-testing#37]
1- Severity High
2- reported by Syrine Hamza
3- when I click forgot password it shows an alert "something went wrong" and thats all. 
4- click forgot password on the student section
5- having a more descriptive message as the email is a working one

**Comment by safya-alzayat** [comment]
duplicate of https://github.com/moar55/se-project-testing/issues/38

**Comment by syrinehamza** [comment]
They are not the same, I posted both. this one is concerning the alert, the other is to say that there is a problem with gmail. please re-open the issue. thanks

**Comment by safya-alzayat** [comment]
i don't get how can it be more descriptive or why ?

**Comment by syrinehamza** [comment]
somehting like "you're email is not valid" or "we can't send the link" or something like that to let the user know that the problem is not with the mail
