### ISSUE TITLE
Flow Problems

### ISSUE THREAD

**Issue by nrizk** [moar55/se-project-testing#63]
Severity : medium
reported by: Nader Rafik
description: When I enter student profile or business profile or updating profile, I'm stuck and can not return back or to the homepage.
Steps to reproduce this issue:
-Login as anyone
-View profile
Expected result: There should be a homepage button, or any button to redirect me anywhere other than the page I am in

**Comment by safya-alzayat** [comment]
duplicate of https://github.com/moar55/se-project-testing/issues/51
