### ISSUE TITLE
No Email sent on Service provider Subscription or acceptance in directory

### ISSUE THREAD

**Issue by rokayaabed** [moar55/se-project-testing#9]
description: 
1. Severity: high

2. Reported by: Rokaya Abed

3. Description: On subscribing the service provider is prompted to wait until accepted in directory however no email is sent on acceptance.

4: Steps to reproduce the issue:

1) Logon into the application
2) Click on Register and Choose service provider
3) Filled the user information fields with invalid email or leave missing fields or  wrong password confirmation
4) Clicked on ‘Submit’ button
5) Accept service provider as admin and no email is sent.

5: Expected result:
Email sent to service provider notifying them with acceptance or rejection.

**Comment by safya-alzayat** [comment]
we can send an email manually
